workflows:
  android-native:
    name: Salehin Attendance APK
    max_build_duration: 60
    instance_type: mac_mini_m2

    scripts:
      - name: Set Android SDK location
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/local.properties"

      - name: Check Gradle Wrapper
        script: |
          echo "=== ROOT FILES ==="
          ls -la
          echo "=== GRADLE FILE ==="
          ls -la gradlew
          file gradlew
          echo "=== GRADLE VERSION ==="
          bash gradlew --version

      - name: Build Android APK
        script: |
          bash gradlew assembleDebug

    artifacts:
      - app/build/outputs/**/*.apk
