workflows:
  android-native:
    name: Salehin Attendance APK
    max_build_duration: 60
    instance_type: mac_mini_m2

    scripts:
      - name: Set Android SDK location
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/local.properties"

      - name: Build Android APK
        script: |
          chmod +x gradlew
          ./gradlew assembleDebug

      - name: Find APK
        script: |
          echo "===== APK FILES ====="
          find "$CM_BUILD_DIR" -type f -name "*.apk" -print

    artifacts:
      - "**/*.apk"
