package ir.salehin.attendance;

import android.content.*;import android.database.*;import android.database.sqlite.*;import org.json.*;import java.io.*;import java.util.*;

public class DB extends SQLiteOpenHelper {
 public DB(Context c){super(c,"salehin.db",null,1);} 
 public void onCreate(SQLiteDatabase d){d.execSQL("CREATE TABLE members(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL,phone TEXT,notes TEXT)");d.execSQL("CREATE TABLE sessions(id INTEGER PRIMARY KEY AUTOINCREMENT,date TEXT NOT NULL,title TEXT,notes TEXT)");d.execSQL("CREATE TABLE attendance(id INTEGER PRIMARY KEY AUTOINCREMENT,session_id INTEGER NOT NULL,member_id INTEGER NOT NULL,status INTEGER NOT NULL,excused INTEGER NOT NULL DEFAULT 0,score INTEGER NOT NULL DEFAULT 0,UNIQUE(session_id,member_id))");}
 public void onUpgrade(SQLiteDatabase d,int a,int b){}
 public long addMember(String n,String p,String note){ContentValues v=new ContentValues();v.put("name",n);v.put("phone",p);v.put("notes",note);return getWritableDatabase().insert("members",null,v);}
 public void updateMember(long id,String n,String p,String note){ContentValues v=new ContentValues();v.put("name",n);v.put("phone",p);v.put("notes",note);getWritableDatabase().update("members",v,"id=?",new String[]{""+id});}
 public void deleteMember(long id){getWritableDatabase().delete("attendance","member_id=?",new String[]{""+id});getWritableDatabase().delete("members","id=?",new String[]{""+id});}
 public long addSession(String date,String title,String note){ContentValues v=new ContentValues();v.put("date",date);v.put("title",title);v.put("notes",note);return getWritableDatabase().insert("sessions",null,v);}
 public void updateSession(long id,String date,String title,String note){ContentValues v=new ContentValues();v.put("date",date);v.put("title",title);v.put("notes",note);getWritableDatabase().update("sessions",v,"id=?",new String[]{""+id});}
 public void deleteSession(long id){getWritableDatabase().delete("attendance","session_id=?",new String[]{""+id});getWritableDatabase().delete("sessions","id=?",new String[]{""+id});}
 public Cursor members(String q){return getReadableDatabase().rawQuery("SELECT * FROM members WHERE name LIKE ? ORDER BY name",new String[]{"%"+q+"%"});}
 public Cursor sessions(){return getReadableDatabase().rawQuery("SELECT * FROM sessions ORDER BY id DESC",null);}
 public Cursor attendance(long sid){return getReadableDatabase().rawQuery("SELECT m.id,m.name,COALESCE(a.status,0) status,COALESCE(a.excused,0) excused,COALESCE(a.score,0) score,a.id aid FROM members m LEFT JOIN attendance a ON a.member_id=m.id AND a.session_id=? ORDER BY m.name",new String[]{""+sid});}
 public void saveAtt(long sid,long mid,int status,int exc,int score){ContentValues v=new ContentValues();v.put("session_id",sid);v.put("member_id",mid);v.put("status",status);v.put("excused",exc);v.put("score",score);getWritableDatabase().insertWithOnConflict("attendance",null,v,SQLiteDatabase.CONFLICT_REPLACE);}
 public int count(String table){Cursor c=getReadableDatabase().rawQuery("SELECT COUNT(*) FROM "+table,null);c.moveToFirst();int n=c.getInt(0);c.close();return n;}
 public double presence(){Cursor c=getReadableDatabase().rawQuery("SELECT SUM(CASE WHEN status IN(1,2) THEN 1 ELSE 0 END)*100.0/NULLIF(COUNT(*),0) FROM attendance",null);c.moveToFirst();double x=c.isNull(0)?0:c.getDouble(0);c.close();return x;}
 public Cursor report(){return getReadableDatabase().rawQuery("SELECT m.id,m.name,COUNT(a.id) total,SUM(CASE WHEN a.status=1 THEN 1 ELSE 0 END) present,SUM(CASE WHEN a.status=2 THEN 1 ELSE 0 END) late,SUM(CASE WHEN a.status=3 AND a.excused=1 THEN 1 ELSE 0 END) excused,SUM(CASE WHEN a.status=3 AND a.excused=0 THEN 1 ELSE 0 END) unexcused,COALESCE(AVG(a.score),0) score FROM members m LEFT JOIN attendance a ON a.member_id=m.id GROUP BY m.id ORDER BY score DESC,present DESC,m.name",null);}
 public void clearAll(){getWritableDatabase().execSQL("DELETE FROM attendance");getWritableDatabase().execSQL("DELETE FROM sessions");getWritableDatabase().execSQL("DELETE FROM members");}
 public JSONObject exportJson() throws Exception {JSONObject o=new JSONObject();JSONArray ms=new JSONArray(),ss=new JSONArray(),aa=new JSONArray();Cursor c=getReadableDatabase().rawQuery("SELECT * FROM members",null);while(c.moveToNext()){JSONObject x=new JSONObject();x.put("id",c.getLong(0));x.put("name",c.getString(1));x.put("phone",c.getString(2));x.put("notes",c.getString(3));ms.put(x);}c.close();c=getReadableDatabase().rawQuery("SELECT * FROM sessions",null);while(c.moveToNext()){JSONObject x=new JSONObject();x.put("id",c.getLong(0));x.put("date",c.getString(1));x.put("title",c.getString(2));x.put("notes",c.getString(3));ss.put(x);}c.close();c=getReadableDatabase().rawQuery("SELECT * FROM attendance",null);while(c.moveToNext()){JSONObject x=new JSONObject();x.put("id",c.getLong(0));x.put("session_id",c.getLong(1));x.put("member_id",c.getLong(2));x.put("status",c.getInt(3));x.put("excused",c.getInt(4));x.put("score",c.getInt(5));aa.put(x);}c.close();o.put("members",ms);o.put("sessions",ss);o.put("attendance",aa);return o;}
 public void importJson(JSONObject o){SQLiteDatabase d=getWritableDatabase();d.beginTransaction();try{clearAll();JSONArray ms=o.getJSONArray("members");for(int i=0;i<ms.length();i++){JSONObject x=ms.getJSONObject(i);ContentValues v=new ContentValues();v.put("id",x.getLong("id"));v.put("name",x.getString("name"));v.put("phone",x.optString("phone"));v.put("notes",x.optString("notes"));d.insert("members",null,v);}JSONArray ss=o.getJSONArray("sessions");for(int i=0;i<ss.length();i++){JSONObject x=ss.getJSONObject(i);ContentValues v=new ContentValues();v.put("id",x.getLong("id"));v.put("date",x.getString("date"));v.put("title",x.optString("title"));v.put("notes",x.optString("notes"));d.insert("sessions",null,v);}JSONArray aa=o.getJSONArray("attendance");for(int i=0;i<aa.length();i++){JSONObject x=aa.getJSONObject(i);ContentValues v=new ContentValues();v.put("id",x.getLong("id"));v.put("session_id",x.getLong("session_id"));v.put("member_id",x.getLong("member_id"));v.put("status",x.getInt("status"));v.put("excused",x.getInt("excused"));v.put("score",x.getInt("score"));d.insert("attendance",null,v);}d.setTransactionSuccessful();}catch(Exception e){throw new RuntimeException(e);}finally{d.endTransaction();}}
}
