package ir.salehin.attendance;

import android.app.*;import android.os.*;import android.content.*;import android.graphics.Color;import android.net.Uri;import android.provider.Settings;import android.view.*;import android.widget.*;import android.text.*;import org.json.*;import java.io.*;import java.nio.charset.StandardCharsets;import android.database.Cursor;

public class MainActivity extends Activity{
 DB db; LinearLayout root,content,nav; TextView title; int blue=Color.rgb(21,101,192); long selectedSession=-1;
 @Override public void onCreate(Bundle b){super.onCreate(b);getWindow().setStatusBarColor(Color.rgb(13,71,161));db=new DB(this);showDashboard();}
 TextView tv(String s,int sp){TextView t=new TextView(this);t.setText(s);t.setTextSize(sp);t.setTextColor(Color.DKGRAY);t.setPadding(20,16,20,16);t.setGravity(Gravity.RIGHT|Gravity.CENTER_VERTICAL);t.setTextDirection(View.TEXT_DIRECTION_RTL);return t;}
 Button btn(String s){Button b=new Button(this);b.setText(s);b.setTextSize(15);b.setAllCaps(false);b.setTextDirection(View.TEXT_DIRECTION_RTL);return b;}
 void base(String name){root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(Color.rgb(248,249,251));root.setLayoutDirection(View.LAYOUT_DIRECTION_RTL); title=tv(name,21);title.setTextColor(Color.WHITE);title.setBackgroundColor(blue);title.setGravity(Gravity.RIGHT|Gravity.CENTER_VERTICAL);root.addView(title,new LinearLayout.LayoutParams(-1,62));content=new LinearLayout(this);content.setOrientation(LinearLayout.VERTICAL);content.setPadding(16,10,16,10);ScrollView sv=new ScrollView(this);sv.addView(content);root.addView(sv,new LinearLayout.LayoutParams(-1,0,1));nav=new LinearLayout(this);nav.setOrientation(LinearLayout.HORIZONTAL);nav.setLayoutDirection(View.LAYOUT_DIRECTION_RTL);String[] ns={"داشبورد","اعضا","جلسات","گزارش","تنظیمات"};for(String n:ns){Button b=btn(n);nav.addView(b,new LinearLayout.LayoutParams(0,58,1));b.setOnClickListener(v->{if(n.equals("داشبورد"))showDashboard();else if(n.equals("اعضا"))showMembers();else if(n.equals("جلسات"))showSessions();else if(n.equals("گزارش"))showReports();else showSettings();});}root.addView(nav);setContentView(root);}
 void addText(String s){content.addView(tv(s,16));}
 TextView stat(String a,String b){TextView t=tv(a+"\n"+b,17);t.setGravity(Gravity.CENTER);t.setBackgroundColor(Color.WHITE);t.setPadding(8,25,8,25);return t;}
 void showDashboard(){base("داشبورد حضور و غیاب");LinearLayout grid=new LinearLayout(this);grid.setOrientation(LinearLayout.VERTICAL);grid.setLayoutDirection(View.LAYOUT_DIRECTION_RTL);String[][] a={{"تعداد اعضا",""+db.count("members")},{"تعداد جلسات",""+db.count("sessions")},{"درصد حضور",""+String.format(java.util.Locale.US,"%.1f",db.presence())+"٪"}};for(String[] x:a){TextView t=stat(x[0],x[1]);grid.addView(t,new LinearLayout.LayoutParams(-1,0,1));}content.addView(grid);Button b=btn("ثبت حضور یک جلسه");b.setOnClickListener(v->showSessions());content.addView(b);addText("تمام اطلاعات روی همین دستگاه ذخیره می‌شود و برنامه برای کارکرد اصلی به اینترنت نیاز ندارد.");}
 void showMembers(){base("مدیریت اعضا");EditText search=new EditText(this);search.setHint("جستجوی نام...");search.setSingleLine();search.setTextDirection(View.TEXT_DIRECTION_RTL);content.addView(search);Button add=btn("＋ افزودن عضو");content.addView(add);LinearLayout list=new LinearLayout(this);list.setOrientation(LinearLayout.VERTICAL);content.addView(list);Runnable refresh=()->{list.removeAllViews();Cursor c=db.members(search.getText().toString());while(c.moveToNext()){long id=c.getLong(0);String n=c.getString(1),p=c.getString(2),notes=c.getString(3);LinearLayout row=new LinearLayout(this);row.setGravity(Gravity.CENTER_VERTICAL);row.setLayoutDirection(View.LAYOUT_DIRECTION_RTL);TextView t=tv(n+(p==null||p.isEmpty()?"":"\n"+p),16);row.addView(t,new LinearLayout.LayoutParams(0,70,1));Button e=btn("ویرایش");Button d=btn("حذف");row.addView(e);row.addView(d);e.setOnClickListener(v->memberDialog(id,n,p,notes));d.setOnClickListener(v->confirm("حذف عضو؟",()->{db.deleteMember(id);refresh.run();}));list.addView(row);}c.close();};search.addTextChangedListener(new TextWatcher(){public void beforeTextChanged(CharSequence s,int a,int c,int d){}public void onTextChanged(CharSequence s,int a,int b,int c){refresh.run();}public void afterTextChanged(Editable e){}});add.setOnClickListener(v->memberDialog(-1,"","",""));refresh.run();}
 void memberDialog(long id,String name,String phone,String notes){LinearLayout f=form();EditText n=field("نام و نام خانوادگی",name),p=field("شماره تماس",phone),no=field("توضیحات",notes);f.addView(n);f.addView(p);f.addView(no);new AlertDialog.Builder(this).setTitle(id<0?"افزودن عضو":"ویرایش عضو").setView(f).setNegativeButton("انصراف",null).setPositiveButton("ذخیره",(d,w)->{if(n.getText().toString().trim().isEmpty()){toast("نام را وارد کنید");return;}if(id<0)db.addMember(n.getText().toString().trim(),p.getText().toString(),no.getText().toString());else db.updateMember(id,n.getText().toString().trim(),p.getText().toString(),no.getText().toString());showMembers();}).show();}
 void showSessions(){base("مدیریت جلسات");Button add=btn("＋ افزودن جلسه");content.addView(add);LinearLayout list=new LinearLayout(this);list.setOrientation(LinearLayout.VERTICAL);content.addView(list);Runnable refresh=()->{list.removeAllViews();Cursor c=db.sessions();while(c.moveToNext()){long id=c.getLong(0);String date=c.getString(1),name=c.getString(2),notes=c.getString(3);LinearLayout row=new LinearLayout(this);row.setLayoutDirection(View.LAYOUT_DIRECTION_RTL);TextView t=tv(date+"  —  "+name,16);row.addView(t,new LinearLayout.LayoutParams(0,72,1));Button open=btn("حضور");Button edit=btn("ویرایش");Button del=btn("حذف");row.addView(open);row.addView(edit);row.addView(del);open.setOnClickListener(v->attendance(id,date,name));edit.setOnClickListener(v->sessionDialog(id,date,name,notes));del.setOnClickListener(v->confirm("حذف جلسه و حضورهای آن؟",()->{db.deleteSession(id);refresh.run();}));list.addView(row);}c.close();};add.setOnClickListener(v->sessionDialog(-1,PersionCalendarFix(),"جلسه",""));refresh.run();}
 String PersionCalendarFix(){return PersianCalendar.today();}
 void sessionDialog(long id,String date,String name,String notes){LinearLayout f=form();EditText dt=field("تاریخ شمسی (yyyy/mm/dd)",date),nm=field("عنوان جلسه",name),no=field("توضیحات",notes);f.addView(dt);f.addView(nm);f.addView(no);new AlertDialog.Builder(this).setTitle(id<0?"افزودن جلسه":"ویرایش جلسه").setView(f).setNegativeButton("انصراف",null).setPositiveButton("ذخیره",(d,w)->{try{PersianCalendar.toGregorian(dt.getText().toString());}catch(Exception e){toast("فرمت تاریخ باید مثل 1405/07/04 باشد");return;}if(id<0)db.addSession(dt.getText().toString(),nm.getText().toString(),no.getText().toString());else db.updateSession(id,dt.getText().toString(),nm.getText().toString(),no.getText().toString());showSessions();}).show();}
 void attendance(long sid,String date,String name){selectedSession=sid;base("ثبت حضور — "+date);addText(name);Cursor c=db.attendance(sid);while(c.moveToNext()){long mid=c.getLong(0);String mn=c.getString(1);int status=c.getInt(2),exc=c.getInt(3),score=c.getInt(4);LinearLayout row=new LinearLayout(this);row.setOrientation(LinearLayout.VERTICAL);row.setPadding(6,8,6,8);row.setBackgroundColor(Color.WHITE);TextView n=tv(mn,17);row.addView(n);Spinner sp=new Spinner(this);String[] ss={"حاضر","تأخیر","غایب"};sp.setAdapter(new ArrayAdapter<String>(this,android.R.layout.simple_spinner_dropdown_item,ss));sp.setSelection(Math.max(0,status-1));row.addView(sp);CheckBox ex=new CheckBox(this);ex.setText("غیبت موجه");ex.setChecked(exc==1);ex.setLayoutDirection(View.LAYOUT_DIRECTION_RTL);ex.setVisibility(status==3?View.VISIBLE:View.GONE);row.addView(ex);EditText sc=field("امتیاز فعالیت ۰ تا ۱۰۰",""+score);sc.setInputType(2);row.addView(sc);sp.setOnItemSelectedListener(new android.widget.AdapterView.OnItemSelectedListener(){public void onNothingSelected(android.widget.AdapterView<?> p){}public void onItemSelected(android.widget.AdapterView<?> p,View v,int pos,long id){ex.setVisibility(pos==2?View.VISIBLE:View.GONE);}});Button save=btn("ذخیره");save.setOnClickListener(v->{int s=sp.getSelectedItemPosition()+1;int z=0;try{z=Integer.parseInt(sc.getText().toString());}catch(Exception ignored){}z=Math.max(0,Math.min(100,z));db.saveAtt(sid,mid,s,s==3&&ex.isChecked()?1:0,z);toast("ثبت شد");});row.addView(save);content.addView(row);}c.close();}
 void showReports(){base("گزارش‌ها");Button ex=btn("خروجی Excel");content.addView(ex);TextView sum=tv("درصد حضور کلی: "+String.format(java.util.Locale.US,"%.1f",db.presence())+"٪",18);content.addView(sum);Cursor c=db.report();int rank=1;while(c.moveToNext()){String n=c.getString(1);int total=c.getInt(2),pr=c.getInt(3),late=c.getInt(4),exc=c.getInt(5),un=c.getInt(6);double sc=c.getDouble(7);double pct=total==0?0:(pr+late)*100.0/total;addText(rank+". "+n+"\nحضور: "+String.format(java.util.Locale.US,"%.1f",pct)+"٪ | حاضر "+pr+" | تأخیر "+late+"\nموجه "+exc+" | غیرموجه "+un+" | امتیاز "+String.format(java.util.Locale.US,"%.1f",sc));rank++;}c.close();ex.setOnClickListener(v->exportExcel());}
 void showSettings(){base("تنظیمات");Button b=btn("پشتیبان‌گیری");Button r=btn("بازیابی پشتیبان");Button del=btn("حذف همه داده‌ها");content.addView(b);content.addView(r);content.addView(del);b.setOnClickListener(v->backup());r.setOnClickListener(v->restore());del.setOnClickListener(v->confirm("همه اعضا، جلسات و حضورها حذف شوند؟",()->{db.clearAll();toast("داده‌ها حذف شدند");showDashboard();}));addText("نسخه 1.0.0 — ذخیره‌سازی محلی SQLite");}
 LinearLayout form(){LinearLayout f=new LinearLayout(this);f.setOrientation(LinearLayout.VERTICAL);f.setPadding(10,0,10,0);f.setLayoutDirection(View.LAYOUT_DIRECTION_RTL);return f;}
 EditText field(String hint,String value){EditText e=new EditText(this);e.setHint(hint);e.setText(value);e.setTextDirection(View.TEXT_DIRECTION_RTL);e.setSingleLine(false);return e;}
 void confirm(String msg,final Runnable yes){new AlertDialog.Builder(this).setMessage(msg).setNegativeButton("انصراف",null).setPositiveButton("تأیید",(d,w)->yes.run()).show();}
 void toast(String s){Toast.makeText(this,s,Toast.LENGTH_SHORT).show();}
 void backup(){Intent i=new Intent(Intent.ACTION_CREATE_DOCUMENT);i.setType("application/json");i.putExtra(Intent.EXTRA_TITLE,"salehin-backup.json");startActivityForResult(i,10);}
 void restore(){Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.setType("application/json");i.addCategory(Intent.CATEGORY_OPENABLE);startActivityForResult(i,11);}
 void exportExcel(){Intent i=new Intent(Intent.ACTION_CREATE_DOCUMENT);i.setType("application/vnd.ms-excel");i.putExtra(Intent.EXTRA_TITLE,"salehin-report.xls");startActivityForResult(i,12);}
 @Override protected void onActivityResult(int req,int res,Intent data){super.onActivityResult(req,res,data);if(res!=RESULT_OK||data==null)return;try{Uri u=data.getData();if(req==10){OutputStream o=getContentResolver().openOutputStream(u);o.write(db.exportJson().toString(2).getBytes(StandardCharsets.UTF_8));o.close();toast("پشتیبان ذخیره شد");}else if(req==11){InputStream in=getContentResolver().openInputStream(u);ByteArrayOutputStream bo=new ByteArrayOutputStream();byte[] buf=new byte[4096];int n;while((n=in.read(buf))>0)bo.write(buf,0,n);in.close();db.importJson(new JSONObject(new String(bo.toByteArray(),StandardCharsets.UTF_8)));toast("بازیابی انجام شد");showDashboard();}else if(req==12){OutputStream o=getContentResolver().openOutputStream(u);writeExcel(o);o.close();toast("گزارش Excel ذخیره شد");}}catch(Exception e){toast("خطا: "+e.getMessage());}}
 void writeExcel(OutputStream o)throws Exception{StringBuilder x=new StringBuilder("<?xml version=\"1.0\"?><Workbook xmlns=\"urn:schemas-microsoft-com:office:spreadsheet\" xmlns:ss=\"urn:schemas-microsoft-com:office:spreadsheet\"><Worksheet ss:Name=\"گزارش\"><Table>");String[] h={"رتبه","عضو","کل ثبت‌ها","حاضر","تأخیر","غیبت موجه","غیبت غیرموجه","درصد حضور","میانگین امتیاز"};x.append("<Row>");for(String s:h)x.append("<Cell><Data ss:Type=\"String\">").append(xml(s)).append("</Data></Cell>");x.append("</Row>");Cursor c=db.report();int r=1;while(c.moveToNext()){int total=c.getInt(2),pr=c.getInt(3),late=c.getInt(4);double pct=total==0?0:(pr+late)*100.0/total;x.append("<Row>");String[] v={""+r,c.getString(1),""+total,""+pr,""+late,""+c.getInt(5),""+c.getInt(6),String.format(java.util.Locale.US,"%.1f",pct),String.format(java.util.Locale.US,"%.1f",c.getDouble(7))};for(String s:v)x.append("<Cell><Data ss:Type=\"String\">").append(xml(s)).append("</Data></Cell>");x.append("</Row>");r++;}c.close();x.append("</Table></Worksheet></Workbook>");o.write(x.toString().getBytes(StandardCharsets.UTF_8));}
 String xml(String s){return s.replace("&","&amp;").replace("<","&lt;").replace(">","&gt;").replace("\"","&quot;");}
}
